// ---------------------------------------------------------------------------
// Built-in object packs
// ---------------------------------------------------------------------------
// Transcribed from map files exported out of the in-game editor, one file per
// group, so the library here matches the library there: Virtual Objects with a
// theme per pack, then Gameplay Objects and Mode Objectives.
//
// Fields
//   type          the "type" string written to the map file. This is the contract.
//   key           unique catalog id; equals `type` unless several library
//                 entries share one type and differ only by `props`
//   objectType    the "$type" discriminator, when it is not a plain MapObject
//   props         extra fields the subtype writes (specificWeapon, style, ...)
//   label         what the library shows
//   category      grouping inside the pack
//   shape         placeholder generator id (see placeholders.js)
//   size          [w, h, d] in metres of the base mesh at scale 1, 1, 1
//   pivot         'base' -> origin on the floor, 'center' -> origin in the middle
//   rotationAxes  'y' yaw only, 'xyz' free
//   floor         the piece is expected to rest on the ground
//   color         placeholder tint
//   defaultScale  scale a freshly placed object gets, read off the reference
//                 files: the player left every scale alone except the solid
//                 box, cylinder and wall, which are sized as you place them
//   icon          sliced sprite name, without extension; see tools/slice-icons.mjs
//   uncertain     `size` is an estimate, not a confirmed mesh dimension
//   hidden        loads and exports normally but is not offered in the library
//
// Base mesh sizes marked `uncertain` are estimates. Map files only store scale
// multipliers, so real mesh dimensions cannot be recovered from them. The
// primitives are the exception: the same scales recur across all eleven themed
// packs at heights that put them exactly on the floor, which pins those meshes
// to one metre units.
//
// The Default pack no longer estimates anything: its sizes are measured off
// reference/GameAssets/Prefabs/*.glb by tools/measure-prefabs.mjs, quoted to
// the millimetre. Two rules govern which number lands here, because the mesh
// and the unit the game scales are not always the same thing.
//
// Where an object rests on the floor with a `center` pivot, the game's own
// placements settle it: every such object in the reference maps sits at
// y = scale.y / 2, so the unit being multiplied is exactly 1 m. Those keep 1,
// even though the meshes measure a little off it — the solid wall's frame
// stands proud at 1.069 x 1.019, and the cylinder's bevelled caps bring it in
// to 0.993. Only the wall's thickness, which no placement constrains, is the
// measured 0.125 rather than the 0.1 previously guessed.
//
// Everything else takes its measured bounding box, since a `base` pivot puts
// the object on the floor regardless of its height. The barriers turn out to
// be 2 m tall rather than the 1.4 m estimated here, and the crates 0.5 m
// rather than 0.6 m.
// ---------------------------------------------------------------------------

export const PACK_SCHEMA_VERSION = 2;

/** Top-level library sections, in the order the game shows them. */
export const PACK_GROUPS = [
  { id: 'virtual', name: 'Virtual Objects' },
  { id: 'gameplay', name: 'Gameplay Objects' },
  { id: 'objectives', name: 'Mode Objectives' },
];

export const BUILTIN_PACKS = [
  {
    id: "default", name: "Default", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "BarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1.14, 2, 1.143], pivot: "base", rotationAxes: "y",
      floor: true, color: "#8B99A6", defaultScale: [1, 1, 1], icon: "Icon_BarrierCorner" },
    { type: "BarrierFull", label: "Barrier Full", category: "Barriers", shape: "barrierFull",
      size: [1.028, 2, 0.258], pivot: "base", rotationAxes: "y", floor: true, color: "#8B99A6",
      defaultScale: [1, 1, 1], icon: "Icon_BarrierNormal" },
    { type: "BarrierLow", label: "Barrier Low", category: "Barriers", shape: "barrierLow",
      size: [1.013, 1.206, 0.258], pivot: "base", rotationAxes: "y", floor: true,
      color: "#8B99A6", defaultScale: [1, 1, 1], icon: "Icon_BarrierLow" },
    { type: "BarrierU", label: "Barrier U", category: "Barriers", shape: "barrierU",
      size: [1.028, 2, 0.258], pivot: "base", rotationAxes: "y", floor: true, color: "#8B99A6",
      defaultScale: [1, 1, 1], icon: "Icon_BarrierUWall" },
    { type: "BarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1.028, 2, 0.258], pivot: "base", rotationAxes: "y",
      floor: true, color: "#8B99A6", defaultScale: [1, 1, 1], icon: "Icon_BarrierWindow" },
    { type: "Tunnel", label: "Tunnel", category: "Structures", shape: "tunnel", size: [1, 1, 1],
      pivot: "center", rotationAxes: "y", floor: true, color: "#8B99A6",
      defaultScale: [1, 2, 1], icon: "Icon_TunnelSolid" },
    { type: "BoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#8B99A6",
      defaultScale: [1, 1, 1], icon: "Icon_BoxSolid_1" },
    { type: "BoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#8B99A6", defaultScale: [1, 1, 1], hidden: true, icon: "Icon_BoxSolid_grounded" },
    { type: "CylinderSolid", label: "Solid Cylinder", category: "Primitives", shape: "cylinder",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#8B99A6",
      defaultScale: [0.5, 2, 0.5], icon: "Icon_CilinderSolid" },
    { type: "CylinderSolidGrounded", label: "Solid Cylinder (Grounded)", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#8B99A6", defaultScale: [0.5, 2, 0.5], hidden: true,
      icon: "Icon_CilinderSolid_grounded" },
    { type: "WallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.125], pivot: "center", rotationAxes: "y", floor: true, color: "#8B99A6",
      defaultScale: [2, 2.5, 1], icon: "Icon_WallSolid_1" },
    { type: "Crate", label: "Crate", category: "Props", shape: "crate", size: [0.5, 0.5, 0.5],
      pivot: "base", rotationAxes: "y", floor: true, color: "#9B8773", defaultScale: [1, 1, 1],
      icon: "Icon_Crate" },
    { type: "DestructibleCrate", label: "Destructible Crate", category: "Props",
      shape: "crateDestructible", size: [0.5, 0.5, 0.5], pivot: "base", rotationAxes: "y",
      floor: true, color: "#A47768", defaultScale: [1, 1, 1], icon: "Icon_CrateDestructable" },
    { type: "DefaultElectricityBox", label: "Electricity Box", category: "Props",
      shape: "electricityBox", size: [0.545, 0.714, 0.44], pivot: "base", rotationAxes: "y",
      floor: true, color: "#719186", defaultScale: [1, 1, 1],
      icon: "Icon_ElectricityBoxDefault" },
    ],
  },
  {
    id: "blue", name: "Blue", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "BlueBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#3E7BB8", defaultScale: [1, 1, 1], uncertain: true },
    { type: "BlueBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#3E7BB8", defaultScale: [1, 1, 1], uncertain: true },
    { type: "BlueBarrierLow", label: "Barrier Low", category: "Barriers", shape: "barrierLow",
      size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true, color: "#3E7BB8",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "BlueBarrierU", label: "Barrier U", category: "Barriers", shape: "barrierU",
      size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true, color: "#3E7BB8",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "BlueBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#3E7BB8", defaultScale: [1, 1, 1], uncertain: true },
    { type: "BlueTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#3E7BB8",
      defaultScale: [1, 2, 1], uncertain: true },
    { type: "BlueBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#3E7BB8",
      defaultScale: [1, 1, 1] },
    { type: "BlueBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#3E7BB8", defaultScale: [1, 1, 1], hidden: true },
    { type: "BlueCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#3E7BB8", defaultScale: [0.5, 2, 0.5] },
    { type: "BlueCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#3E7BB8", defaultScale: [0.5, 2, 0.5],
      hidden: true },
    { type: "BlueWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#3E7BB8",
      defaultScale: [2, 2.5, 1], uncertain: true },
    { type: "BlueCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#787A7C",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "BlueDestructibleCrate", label: "Destructible Crate", category: "Props",
      shape: "crateDestructible", size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y",
      floor: true, color: "#816A71", defaultScale: [1, 1, 1], uncertain: true },
    { type: "BlueElectricityBox", label: "Electricity Box", category: "Props",
      shape: "electricityBox", size: [0.4, 0.6, 0.28], pivot: "base", rotationAxes: "y",
      floor: true, color: "#4F838E", defaultScale: [1, 1, 1], uncertain: true },
    ],
  },
  {
    id: "orange", name: "Orange", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "OrangeBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#D5822F", defaultScale: [1, 1, 1], uncertain: true },
    { type: "OrangeBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#D5822F", defaultScale: [1, 1, 1], uncertain: true },
    { type: "OrangeBarrierLow", label: "Barrier Low", category: "Barriers", shape: "barrierLow",
      size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true, color: "#D5822F",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "OrangeBarrierU", label: "Barrier U", category: "Barriers", shape: "barrierU",
      size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true, color: "#D5822F",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "OrangeBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#D5822F", defaultScale: [1, 1, 1], uncertain: true },
    { type: "OrangeTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#D5822F",
      defaultScale: [1, 2, 1], uncertain: true },
    { type: "OrangeBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#D5822F",
      defaultScale: [1, 1, 1] },
    { type: "OrangeBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#D5822F", defaultScale: [1, 1, 1], hidden: true },
    { type: "OrangeCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#D5822F", defaultScale: [0.5, 2, 0.5] },
    { type: "OrangeCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#D5822F", defaultScale: [0.5, 2, 0.5],
      hidden: true },
    { type: "OrangeWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#D5822F",
      defaultScale: [2, 2.5, 1], uncertain: true },
    { type: "OrangeCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#BC7D3E",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "OrangeDestructibleCrate", label: "Destructible Crate", category: "Props",
      shape: "crateDestructible", size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y",
      floor: true, color: "#C56D33", defaultScale: [1, 1, 1], uncertain: true },
    { type: "OrangeElectricityBox", label: "Electricity Box", category: "Props",
      shape: "electricityBox", size: [0.4, 0.6, 0.28], pivot: "base", rotationAxes: "y",
      floor: true, color: "#928650", defaultScale: [1, 1, 1], uncertain: true },
    ],
  },
  {
    id: "purple", name: "Purple", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "PurpleBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#7C5CB0", defaultScale: [1, 1, 1], uncertain: true },
    { type: "PurpleBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#7C5CB0", defaultScale: [1, 1, 1], uncertain: true },
    { type: "PurpleBarrierLow", label: "Barrier Low", category: "Barriers", shape: "barrierLow",
      size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true, color: "#7C5CB0",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "PurpleBarrierU", label: "Barrier U", category: "Barriers", shape: "barrierU",
      size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true, color: "#7C5CB0",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "PurpleBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#7C5CB0", defaultScale: [1, 1, 1], uncertain: true },
    { type: "PurpleTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#7C5CB0",
      defaultScale: [1, 2, 1], uncertain: true },
    { type: "PurpleBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#7C5CB0",
      defaultScale: [1, 1, 1] },
    { type: "PurpleBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#7C5CB0", defaultScale: [1, 1, 1], hidden: true },
    { type: "PurpleCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#7C5CB0", defaultScale: [0.5, 2, 0.5] },
    { type: "PurpleCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#7C5CB0", defaultScale: [0.5, 2, 0.5],
      hidden: true },
    { type: "PurpleWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#7C5CB0",
      defaultScale: [2, 2.5, 1], uncertain: true },
    { type: "PurpleCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#946C78",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "PurpleDestructibleCrate", label: "Destructible Crate", category: "Props",
      shape: "crateDestructible", size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y",
      floor: true, color: "#9D5C6D", defaultScale: [1, 1, 1], uncertain: true },
    { type: "PurpleElectricityBox", label: "Electricity Box", category: "Props",
      shape: "electricityBox", size: [0.4, 0.6, 0.28], pivot: "base", rotationAxes: "y",
      floor: true, color: "#6A758A", defaultScale: [1, 1, 1], uncertain: true },
    ],
  },
  {
    id: "camo", name: "Camo", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "CamoBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#6E7A48", defaultScale: [1, 1, 1], uncertain: true },
    { type: "CamoBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#6E7A48", defaultScale: [1, 1, 1], uncertain: true },
    { type: "CamoBarrierLow", label: "Barrier Low", category: "Barriers", shape: "barrierLow",
      size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true, color: "#6E7A48",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "CamoBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#6E7A48", defaultScale: [1, 1, 1], uncertain: true },
    { type: "CamoBarrierX", label: "Barrier X", category: "Barriers", shape: "barrierX",
      size: [1.4, 1.4, 1.4], pivot: "base", rotationAxes: "y", floor: true, color: "#6E7A48",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "CamoTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#6E7A48",
      defaultScale: [1, 2, 1], uncertain: true },
    { type: "CamoBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#6E7A48",
      defaultScale: [1, 1, 1] },
    { type: "CamoBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#6E7A48", defaultScale: [1, 1, 1], hidden: true },
    { type: "CamoCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#6E7A48", defaultScale: [0.5, 2, 0.5] },
    { type: "CamoCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#6E7A48", defaultScale: [0.5, 2, 0.5],
      hidden: true },
    { type: "CamoWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#6E7A48",
      defaultScale: [2, 2.5, 1], uncertain: true },
    { type: "CamoCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#8E7949",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "CamoCrateBig", label: "Crate Big", category: "Props", shape: "crateBig",
      size: [0.9, 0.9, 0.9], pivot: "base", rotationAxes: "y", floor: true, color: "#8E7949",
      defaultScale: [1, 1, 1], uncertain: true },
    ],
  },
  {
    id: "mykea", name: "Mykea", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "MYKEABarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#C9A97A", defaultScale: [1, 1, 1], uncertain: true },
    { type: "MYKEABarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#C9A97A", defaultScale: [1, 1, 1], uncertain: true },
    { type: "MYKEABarrierLow", label: "Barrier Low", category: "Barriers", shape: "barrierLow",
      size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true, color: "#C9A97A",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "MYKEABarrierU", label: "Barrier U", category: "Barriers", shape: "barrierU",
      size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true, color: "#C9A97A",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "MYKEABarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#C9A97A", defaultScale: [1.2337, 1.2337, 1.2337], uncertain: true },
    { type: "MYKEATunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#C9A97A",
      defaultScale: [1, 2, 1], uncertain: true },
    { type: "MYKEABoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#C9A97A",
      defaultScale: [1, 1, 1] },
    { type: "MYKEABoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#C9A97A", defaultScale: [1, 1, 1], hidden: true },
    { type: "MYKEACylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#C9A97A", defaultScale: [0.5, 2, 0.5] },
    { type: "MYKEACylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#C9A97A", defaultScale: [0.5, 2, 0.5],
      hidden: true },
    { type: "MYKEAWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#C9A97A",
      defaultScale: [2, 2.5, 1], uncertain: true },
    { type: "MYKEACushion", label: "Cushion", category: "Props", shape: "cushion",
      size: [0.5, 0.18, 0.5], pivot: "base", rotationAxes: "y", floor: true, color: "#CDA77C",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "MYKEAOttoman", label: "Ottoman", category: "Props", shape: "ottoman",
      size: [0.6, 0.42, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#C49868",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "MYKEASofa", label: "Sofa", category: "Props", shape: "sofa",
      size: [1.6, 0.78, 0.82], pivot: "base", rotationAxes: "y", floor: true, color: "#C49868",
      defaultScale: [1, 1, 1], uncertain: true },
    ],
  },
  {
    id: "graffiti", name: "Graffiti", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "GraffitiBarrierBroken", label: "Barrier Broken", category: "Barriers",
      shape: "barrierBroken", size: [1, 1.1, 0.16], pivot: "base", rotationAxes: "y",
      floor: true, color: "#7F8B97", defaultScale: [1, 1, 1], uncertain: true },
    { type: "GraffitiBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#7F8B97", defaultScale: [1, 1, 1], uncertain: true },
    { type: "GraffitiBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#7F8B97", defaultScale: [1, 1, 1], uncertain: true },
    { type: "GraffitiBarrierLow", label: "Barrier Low", category: "Barriers",
      shape: "barrierLow", size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#7F8B97", defaultScale: [1, 1, 1], uncertain: true },
    { type: "GraffitiBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#7F8B97", defaultScale: [1, 1, 1], uncertain: true },
    { type: "GraffitiTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#7F8B97",
      defaultScale: [1, 2, 1], uncertain: true },
    { type: "GraffitiBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#7F8B97",
      defaultScale: [1, 1, 1] },
    { type: "GraffitiBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#7F8B97", defaultScale: [1, 1, 1], hidden: true },
    { type: "GraffitiCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#7F8B97", defaultScale: [0.5, 2, 0.5] },
    { type: "GraffitiCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#7F8B97", defaultScale: [0.5, 2, 0.5],
      hidden: true },
    { type: "GraffitiWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#7F8B97",
      defaultScale: [2, 2.5, 1], uncertain: true },
    { type: "GraffitiBarrel", label: "Barrel", category: "Props", shape: "barrel",
      size: [0.56, 0.86, 0.56], pivot: "base", rotationAxes: "y", floor: true, color: "#857965",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "GraffitiCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#96816D",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "GraffitiPigeon", label: "Pigeon", category: "Props", shape: "pigeon",
      size: [0.18, 0.26, 0.34], pivot: "base", rotationAxes: "y", floor: true, color: "#8C98A4",
      defaultScale: [1, 1, 1], uncertain: true },
    ],
  },
  {
    id: "paintball", name: "Paintball", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "PaintballBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#34A57C", defaultScale: [1, 1, 1], uncertain: true },
    { type: "PaintballBarrierD", label: "Barrier D", category: "Barriers", shape: "barrierD",
      size: [1.2, 1.4, 0.9], pivot: "base", rotationAxes: "y", floor: true, color: "#34A57C",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "PaintballBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#34A57C", defaultScale: [1, 1, 1], uncertain: true },
    { type: "PaintballBarrierLow", label: "Barrier Low", category: "Barriers",
      shape: "barrierLow", size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#34A57C", defaultScale: [1, 1, 1], uncertain: true },
    { type: "PaintballBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#34A57C", defaultScale: [1, 1, 1], uncertain: true },
    { type: "PaintballTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#34A57C",
      defaultScale: [1, 2, 1], uncertain: true },
    { type: "PaintballBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#34A57C",
      defaultScale: [1, 1, 1] },
    { type: "PaintballBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#34A57C", defaultScale: [1, 1, 1], hidden: true },
    { type: "PaintballCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#34A57C", defaultScale: [0.5, 2, 0.5] },
    { type: "PaintballCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#34A57C", defaultScale: [0.5, 2, 0.5],
      hidden: true },
    { type: "PaintballWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#34A57C",
      defaultScale: [2, 2.5, 1], uncertain: true },
    { type: "PaintballCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#748D61",
      defaultScale: [1, 1, 1], uncertain: true },
    ],
  },
  {
    id: "wildwest", name: "Wild West", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "WildWestBarrierBroken", label: "Barrier Broken", category: "Barriers",
      shape: "barrierBroken", size: [1, 1.1, 0.16], pivot: "base", rotationAxes: "y",
      floor: true, color: "#9E7346", defaultScale: [1, 1, 1], uncertain: true },
    { type: "WildWestBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#9E7346", defaultScale: [1, 1, 1], uncertain: true },
    { type: "WildWestBarrierDoor", label: "Barrier Door", category: "Barriers",
      shape: "barrierDoor", size: [1.1, 1.3, 0.16], pivot: "base", rotationAxes: "y",
      floor: true, color: "#9E7346", defaultScale: [1, 1, 1], uncertain: true },
    { type: "WildWestBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#9E7346", defaultScale: [1, 1, 1], uncertain: true },
    { type: "WildWestBarrierLow", label: "Barrier Low", category: "Barriers",
      shape: "barrierLow", size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#9E7346", defaultScale: [1, 1, 1], uncertain: true },
    { type: "WildWestTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#9E7346",
      defaultScale: [1, 2, 1], uncertain: true },
    { type: "WildWestBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#9E7346",
      defaultScale: [1, 1, 1] },
    { type: "WildWestBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#9E7346", defaultScale: [1, 1, 1], hidden: true },
    { type: "WildWestCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#9E7346", defaultScale: [0.5, 2, 0.5] },
    { type: "WildWestCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#9E7346", defaultScale: [0.5, 2, 0.5],
      hidden: true },
    { type: "WildWestWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#9E7346",
      defaultScale: [2, 2.5, 1], uncertain: true },
    { type: "WildWestBarrel", label: "Barrel", category: "Props", shape: "barrel",
      size: [0.56, 0.86, 0.56], pivot: "base", rotationAxes: "y", floor: true, color: "#936E41",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "WildWestCacti", label: "Cacti", category: "Props", shape: "cacti",
      size: [0.7, 1.5, 0.5], pivot: "base", rotationAxes: "y", floor: true, color: "#7B804D",
      defaultScale: [1, 1, 1], uncertain: true },
    ],
  },
  {
    id: "hatchetcorp", name: "Hatchet Corp", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "HatchetCorpBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#6B7784", defaultScale: [1, 1, 1], uncertain: true },
    { type: "HatchetCorpBarrierDoorway", label: "Barrier Doorway", category: "Barriers",
      shape: "barrierDoorway", size: [1.4, 2.1, 0.16], pivot: "base", rotationAxes: "y",
      floor: true, color: "#6B7784", defaultScale: [1, 1, 1], uncertain: true },
    { type: "HatchetCorpBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#6B7784", defaultScale: [1, 1, 1], uncertain: true },
    { type: "HatchetCorpBarrierL", label: "Barrier L", category: "Barriers", shape: "barrierL",
      size: [1.4, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true, color: "#6B7784",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "HatchetCorpBarrierSlope", label: "Barrier Slope", category: "Barriers",
      shape: "barrierSlope", size: [1, 1, 1.2], pivot: "base", rotationAxes: "y", floor: true,
      color: "#6B7784", defaultScale: [1, 1, 1], uncertain: true },
    { type: "HatchetCorpBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#6B7784", defaultScale: [1, 1, 1], uncertain: true },
    { type: "HatchetCorpPillar", label: "Pillar", category: "Structures", shape: "pillar",
      size: [0.5, 2.4, 0.5], pivot: "base", rotationAxes: "y", floor: true, color: "#6B7784",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "HatchetCorpTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#6B7784",
      defaultScale: [1, 2, 1], uncertain: true },
    { type: "HatchetCorpBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#6B7784",
      defaultScale: [1, 1, 1] },
    { type: "HatchetCorpBoxSolidGrounded", label: "Solid Box (Grounded)",
      category: "Primitives", shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y",
      floor: true, color: "#6B7784", defaultScale: [1, 1, 1], hidden: true },
    { type: "HatchetCorpCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#6B7784", defaultScale: [0.5, 2, 0.5] },
    { type: "HatchetCorpCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#6B7784", defaultScale: [0.5, 2, 0.5],
      hidden: true },
    { type: "HatchetCorpWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#6B7784",
      defaultScale: [2, 2.5, 1], uncertain: true },
    { type: "HatchetCorpCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#8D7864",
      defaultScale: [1, 1, 1], uncertain: true },
    ],
  },
  {
    id: "corrupted", name: "Corrupted Technology", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "CenterStationCPU", label: "Center Station CPU", category: "Machines",
      shape: "centerStationCpu", size: [1.2, 1.6, 1.2], pivot: "base", rotationAxes: "y",
      floor: true, color: "#56708C", defaultScale: [1, 1, 1], uncertain: true },
    { type: "CoffeeMachine", label: "Coffee Machine", category: "Machines",
      shape: "coffeeMachine", size: [0.5, 1.4, 0.5], pivot: "base", rotationAxes: "y",
      floor: true, color: "#56708C", defaultScale: [1, 1, 1], uncertain: true },
    { type: "Console", label: "Console", category: "Machines", shape: "console",
      size: [1.1, 1.1, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#56708C",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "Recuperator", label: "Recuperator", category: "Machines", shape: "recuperator",
      size: [1, 1.8, 1], pivot: "base", rotationAxes: "y", floor: true, color: "#56708C",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "SampleAnalysisMachine", label: "Sample Analysis Machine", category: "Machines",
      shape: "sampleAnalysis", size: [1.2, 1.7, 0.8], pivot: "base", rotationAxes: "y",
      floor: true, color: "#56708C", defaultScale: [1, 1, 1], uncertain: true },
    { type: "Server", label: "Server", category: "Machines", shape: "server",
      size: [0.7, 1.9, 0.9], pivot: "base", rotationAxes: "y", floor: true, color: "#56708C",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "WireContainer", label: "Wire Container", category: "Machines",
      shape: "wireContainer", size: [1, 1.1, 0.7], pivot: "base", rotationAxes: "y",
      floor: true, color: "#56708C", defaultScale: [1, 1, 1], uncertain: true },
    { type: "Chopper", label: "Chopper", category: "Vehicles", shape: "chopper",
      size: [3.4, 2.6, 5.2], pivot: "base", rotationAxes: "y", floor: true, color: "#56708C",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "Tank", label: "Tank", category: "Vehicles", shape: "tank", size: [2.8, 2.2, 5],
      pivot: "base", rotationAxes: "y", floor: true, color: "#56708C", defaultScale: [1, 1, 1],
      uncertain: true },
    { type: "Truck", label: "Truck", category: "Vehicles", shape: "truck", size: [2.2, 2.5, 5],
      pivot: "base", rotationAxes: "y", floor: true, color: "#56708C", defaultScale: [1, 1, 1],
      uncertain: true },
    { type: "CrystalCircle", label: "Crystal Circle", category: "Crystals",
      shape: "crystalCircle", size: [1.2, 1.5, 1.2], pivot: "base", rotationAxes: "y",
      floor: true, color: "#7C76BA", defaultScale: [1, 1, 1], uncertain: true },
    { type: "CrystalHalfCircle", label: "Crystal Half Circle", category: "Crystals",
      shape: "crystalHalf", size: [1.2, 1.4, 0.7], pivot: "base", rotationAxes: "y",
      floor: true, color: "#7C76BA", defaultScale: [1, 1, 1], uncertain: true },
    { type: "CrystalSmall", label: "Crystal Small", category: "Crystals", shape: "crystalSmall",
      size: [0.7, 1.1, 0.7], pivot: "base", rotationAxes: "y", floor: true, color: "#7C76BA",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "DarkCrystalCircle", label: "Dark Crystal Circle", category: "Crystals",
      shape: "crystalCircle", size: [1.2, 1.5, 1.2], pivot: "base", rotationAxes: "y",
      floor: true, color: "#595B89", defaultScale: [0.9195, 0.9195, 0.9195], uncertain: true },
    { type: "DarkCrystalHalfCircle", label: "Dark Crystal Half Circle", category: "Crystals",
      shape: "crystalHalf", size: [1.2, 1.4, 0.7], pivot: "base", rotationAxes: "y",
      floor: true, color: "#595B89", defaultScale: [1, 1, 1], uncertain: true },
    { type: "DarkCrystalSmall", label: "Dark Crystal Small", category: "Crystals",
      shape: "crystalSmall", size: [0.7, 1.1, 0.7], pivot: "base", rotationAxes: "y",
      floor: true, color: "#595B89", defaultScale: [1, 1, 1], uncertain: true },
    ],
  },
  {
    id: "gameplay", name: "Gameplay Objects", group: "gameplay", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:All", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "All" }, label: "Any Weapon", category: "Weapon Spawns",
      shape: "spawnAll", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y", floor: true,
      color: "#E8C547", defaultScale: [1, 1, 1], uncertain: true },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:Flashbang",
      objectType: "WeaponSpawnPoint", props: { specificWeapon: "Flashbang" },
      label: "Flashbang", category: "Weapon Spawns", shape: "spawnFlashbang",
      size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y", floor: true, color: "#D8C77A",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:Grenade", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "Grenade" }, label: "Grenade", category: "Weapon Spawns",
      shape: "spawnGrenade", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y",
      floor: true, color: "#7FB77E", defaultScale: [1, 1, 1], uncertain: true },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:Handgun", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "Handgun" }, label: "Handgun", category: "Weapon Spawns",
      shape: "spawnHandgun", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y",
      floor: true, color: "#4EC9E0", defaultScale: [1, 1, 1], uncertain: true },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:Healthpack",
      objectType: "WeaponSpawnPoint", props: { specificWeapon: "Healthpack" },
      label: "Health Pack", category: "Weapon Spawns", shape: "spawnHealthpack",
      size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y", floor: true, color: "#5AD6A0",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:RiotShield",
      objectType: "WeaponSpawnPoint", props: { specificWeapon: "RiotShield" },
      label: "Riot Shield", category: "Weapon Spawns", shape: "spawnRiotShield",
      size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y", floor: true, color: "#9AA7B4",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:RPG", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "RPG" }, label: "RPG", category: "Weapon Spawns",
      shape: "spawnRpg", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y", floor: true,
      color: "#4EC9E0", defaultScale: [1, 1, 1], uncertain: true },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:Shotgun", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "Shotgun" }, label: "Shotgun", category: "Weapon Spawns",
      shape: "spawnShotgun", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y",
      floor: true, color: "#4EC9E0", defaultScale: [1, 1, 1], uncertain: true },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:SMG", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "SMG" }, label: "SMG", category: "Weapon Spawns",
      shape: "spawnSmg", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y", floor: true,
      color: "#4EC9E0", defaultScale: [1, 1, 1], uncertain: true },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:Sniper", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "Sniper" }, label: "Sniper", category: "Weapon Spawns",
      shape: "spawnSniper", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y",
      floor: true, color: "#4EC9E0", defaultScale: [1, 1, 1], uncertain: true },
    { type: "DamageBox", objectType: "DamageBox", props: { style: "Red" }, label: "Damage Box",
      category: "Hazards", shape: "damageBox", size: [1, 1, 1], pivot: "center",
      rotationAxes: "xyz", floor: false, color: "#E0574B", defaultScale: [1, 1, 1],
      uncertain: true },
    { type: "DamageBoxTeam1", objectType: "DamageBox", props: { style: "Blue" },
      label: "Damage Box Team 1", category: "Hazards", shape: "damageBox", size: [1, 1, 1],
      pivot: "center", rotationAxes: "xyz", floor: false, color: "#4A90D9",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "DamageBoxTeam2", objectType: "DamageBox", props: { style: "Orange" },
      label: "Damage Box Team 2", category: "Hazards", shape: "damageBox", size: [1, 1, 1],
      pivot: "center", rotationAxes: "xyz", floor: false, color: "#E08A3C",
      defaultScale: [1, 1, 1], uncertain: true },
    { type: "ExplosiveBarrel", label: "Explosive Barrel", category: "Hazards",
      shape: "explosiveBarrel", size: [0.56, 0.86, 0.56], pivot: "base", rotationAxes: "y",
      floor: true, color: "#C4452F", defaultScale: [1, 1, 1], uncertain: true },
    { type: "Jumbotron", label: "Jumbotron", category: "Emplacements", shape: "jumbotron",
      size: [1.4, 0.9, 0.22], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#3A4C5A", defaultScale: [1, 1, 1], uncertain: true },
    { type: "Minigun", label: "Minigun", category: "Emplacements", shape: "minigun",
      size: [0.8, 1.3, 0.9], pivot: "base", rotationAxes: "y", floor: true, color: "#6E7C8A",
      defaultScale: [0.9, 0.9, 0.9], uncertain: true },
    ],
  },
  {
    id: "objectives", name: "Mode Objectives", group: "objectives", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "PlayerSpawnZoneTeam1", label: "Player Spawn Zone Team 1", category: "Spawn Zones",
      shape: "spawnZone", size: [1.4, 1, 1.4], pivot: "base", rotationAxes: "y", floor: true,
      color: "#4A90D9", defaultScale: [1, 1, 1], uncertain: true },
    { type: "PlayerSpawnZoneTeam2", label: "Player Spawn Zone Team 2", category: "Spawn Zones",
      shape: "spawnZone", size: [1.4, 1, 1.4], pivot: "base", rotationAxes: "y", floor: true,
      color: "#E08A3C", defaultScale: [1, 1, 1], uncertain: true },
    { type: "EnemySpawnPoint", key: "EnemySpawnPoint:Default", objectType: "EnemySpawnPoint",
      props: { enemyTypes: "All", behaviour: "Default" }, label: "Enemy Spawn",
      category: "Enemy Spawns", shape: "enemySpawn", size: [0.7, 1.1, 0.7], pivot: "base",
      rotationAxes: "y", floor: true, color: "#C0553F", defaultScale: [1, 1, 1],
      uncertain: true },
    { type: "EnemySpawnPoint", key: "EnemySpawnPoint:Aggresive", objectType: "EnemySpawnPoint",
      props: { enemyTypes: "All", behaviour: "Aggresive" }, label: "Enemy Spawn (Aggresive)",
      category: "Enemy Spawns", shape: "enemySpawn", size: [0.7, 1.1, 0.7], pivot: "base",
      rotationAxes: "y", floor: true, color: "#E0574B", defaultScale: [1, 1, 1],
      uncertain: true },
    { type: "EnemySpawnPoint", key: "EnemySpawnPoint:Stationary", objectType: "EnemySpawnPoint",
      props: { enemyTypes: "All", behaviour: "Stationary" }, label: "Enemy Spawn (Stationary)",
      category: "Enemy Spawns", shape: "enemySpawn", size: [0.7, 1.1, 0.7], pivot: "base",
      rotationAxes: "y", floor: true, color: "#8A6A5A", defaultScale: [1, 1, 1],
      uncertain: true },
    { type: "DominationZoneA", label: "Domination Zone A", category: "Domination",
      shape: "dominationZoneA", size: [1.5, 1, 1.5], pivot: "base", rotationAxes: "y",
      floor: true, color: "#E8C547", defaultScale: [1, 1, 1], uncertain: true },
    { type: "DominationZoneB", label: "Domination Zone B", category: "Domination",
      shape: "dominationZoneB", size: [1.5, 1, 1.5], pivot: "base", rotationAxes: "y",
      floor: true, color: "#B98FD6", defaultScale: [1, 1, 1], uncertain: true },
    { type: "DominationZoneC", label: "Domination Zone C", category: "Domination",
      shape: "dominationZoneC", size: [1.5, 1, 1.5], pivot: "base", rotationAxes: "y",
      floor: true, color: "#5AD6A0", defaultScale: [1, 1, 1], uncertain: true },
    { type: "CaptureFlagSpawnTeam1", label: "Capture Flag Spawn Team 1",
      category: "Capture The Flag", shape: "flagSpawn", size: [0.6, 1.8, 0.6], pivot: "base",
      rotationAxes: "y", floor: true, color: "#4A90D9", defaultScale: [1, 1, 1],
      uncertain: true },
    { type: "CaptureFlagSpawnTeam2", label: "Capture Flag Spawn Team 2",
      category: "Capture The Flag", shape: "flagSpawn", size: [0.6, 1.8, 0.6], pivot: "base",
      rotationAxes: "y", floor: true, color: "#E08A3C", defaultScale: [1, 1, 1],
      uncertain: true },
    ],
  },
];
