// ---------------------------------------------------------------------------
// Built-in object packs
// ---------------------------------------------------------------------------
// Transcribed from map files exported out of the in-game editor, one file per
// group, so the library here matches the library there: Virtual Objects with a
// theme per pack, then Gameplay Objects and Mode Objectives.
//
// Fields
//   type          the "type" string written to the map file. This is the contract.
//   key           unique catalog id; equals `type` unless several library
//                 entries share one type and differ only by `props`
//   objectType    the "$type" discriminator, when it is not a plain MapObject
//   props         extra fields the subtype writes (specificWeapon, style, ...)
//   label         what the library shows
//   category      grouping inside the pack
//   shape         placeholder generator id (see placeholders.js)
//   size          [w, h, d] in metres of the base mesh at scale 1, 1, 1
//   pivot         'base' -> origin on the floor, 'center' -> origin in the middle
//   rotationAxes  'y' yaw only, 'xyz' free
//   floor         the piece is expected to rest on the ground
//   color         placeholder tint
//   defaultScale  scale a freshly placed object gets, read off the reference
//                 files: the player left every scale alone except the solid
//                 box, cylinder and wall, which are sized as you place them
//   icon          sliced sprite name, without extension; see tools/slice-icons.mjs
//   model         prefab basename in reference/GameAssets/Prefabs, without .glb
//   texture       base-colour map in reference/GameAssets/Textures
//   uncertain     `size` is an estimate, not a confirmed mesh dimension
//   hidden        loads and exports normally but is not offered in the library
//
// `model`, `texture` and `icon` are resolved by tools/match-assets.mjs and are
// pointers into the gitignored asset dump, so the editor still runs without it:
// nothing loads them yet and the procedural placeholder stands in. They are not
// derivable from the type string — the catalog is keyed by what the game writes
// and the art by whatever the artists called it, and the two agree about half
// the time. MYKEA is Indoor, Graffiti is StreetStyle, Hatchet Corp is HatCo,
// Camo is Military in the icons. Textures are not name-matched at all: a GLB
// embeds its images with no filename, so each is hashed and looked up against
// Textures/, which is an identity rather than a guess.
//
// Note these sit outside `props`. `props` is the set of extra fields the game
// itself writes for a subtype, and anything added to it lands in exported map
// files.
//
// Base mesh sizes marked `uncertain` are estimates. Map files only store scale
// multipliers, so real mesh dimensions cannot be recovered from them. The
// primitives are the exception: the same scales recur across all eleven themed
// packs at heights that put them exactly on the floor, which pins those meshes
// to one metre units.
//
// The Default pack no longer estimates anything: its sizes are measured off
// reference/GameAssets/Prefabs/*.glb by tools/measure-prefabs.mjs, quoted to
// the millimetre. Two rules govern which number lands here, because the mesh
// and the unit the game scales are not always the same thing.
//
// Where an object rests on the floor with a `center` pivot, the game's own
// placements settle it: every such object in the reference maps sits at
// y = scale.y / 2, so the unit being multiplied is exactly 1 m. Those keep 1,
// even though the meshes measure a little off it — the solid wall's frame
// stands proud at 1.069 x 1.019, and the cylinder's bevelled caps bring it in
// to 0.993. Only the wall's thickness, which no placement constrains, is the
// measured 0.125 rather than the 0.1 previously guessed.
//
// Everything else takes its measured bounding box, since a `base` pivot puts
// the object on the floor regardless of its height. The barriers turn out to
// be 2 m tall rather than the 1.4 m estimated here, and the crates 0.5 m
// rather than 0.6 m.
// ---------------------------------------------------------------------------

export const PACK_SCHEMA_VERSION = 2;

/** Top-level library sections, in the order the game shows them. */
export const PACK_GROUPS = [
  { id: 'virtual', name: 'Virtual Objects' },
  { id: 'gameplay', name: 'Gameplay Objects' },
  { id: 'objectives', name: 'Mode Objectives' },
];

export const BUILTIN_PACKS = [
  {
    id: "default", name: "Default", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "BarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1.14, 2, 1.143], pivot: "base", rotationAxes: "y",
      floor: true, color: "#8B99A6", defaultScale: [1, 1, 1], icon: "Icon_BarrierCorner",
      model: "BarrierCorner", texture: "BarrierMat_Diffuse_0.png" },
    { type: "BarrierFull", label: "Barrier Full", category: "Barriers", shape: "barrierFull",
      size: [1.028, 2, 0.258], pivot: "base", rotationAxes: "y", floor: true, color: "#8B99A6",
      defaultScale: [1, 1, 1], icon: "Icon_BarrierNormal",
      model: "BarrierFull", texture: "BarrierMat_Diffuse_0.png" },
    { type: "BarrierLow", label: "Barrier Low", category: "Barriers", shape: "barrierLow",
      size: [1.013, 1.206, 0.258], pivot: "base", rotationAxes: "y", floor: true,
      color: "#8B99A6", defaultScale: [1, 1, 1], icon: "Icon_BarrierLow",
      model: "BarrierLow", texture: "BarrierMat_Diffuse_0.png" },
    { type: "BarrierU", label: "Barrier U", category: "Barriers", shape: "barrierU",
      size: [1.028, 2, 0.258], pivot: "base", rotationAxes: "y", floor: true, color: "#8B99A6",
      defaultScale: [1, 1, 1], icon: "Icon_BarrierUWall",
      model: "BarrierU", texture: "BarrierMat_Diffuse.png" },
    { type: "BarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1.028, 2, 0.258], pivot: "base", rotationAxes: "y",
      floor: true, color: "#8B99A6", defaultScale: [1, 1, 1], icon: "Icon_BarrierWindow",
      model: "BarrierWindow", texture: "BarrierMat_Diffuse.png" },
    { type: "Tunnel", label: "Tunnel", category: "Structures", shape: "tunnel", size: [1, 1, 1],
      pivot: "center", rotationAxes: "y", floor: true, color: "#8B99A6",
      defaultScale: [1, 2, 1], icon: "Icon_TunnelSolid",
      model: "Tunnel", texture: "DefaultGreenMetal_Diffuse.png" },
    { type: "BoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#8B99A6",
      defaultScale: [1, 1, 1], icon: "Icon_BoxSolid_1",
      model: "BoxSolid", texture: "DefaultGreenMetal_Diffuse.png" },
    { type: "BoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#8B99A6", defaultScale: [1, 1, 1], hidden: true, icon: "Icon_BoxSolid_grounded",
      model: "BoxSolidGrounded", texture: "DefaultGreenMetal_Diffuse.png" },
    { type: "CylinderSolid", label: "Solid Cylinder", category: "Primitives", shape: "cylinder",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#8B99A6",
      defaultScale: [0.5, 2, 0.5], icon: "Icon_CilinderSolid",
      model: "CylinderSolid", texture: "DefaultGreenMetal_Diffuse.png" },
    { type: "CylinderSolidGrounded", label: "Solid Cylinder (Grounded)", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#8B99A6", defaultScale: [0.5, 2, 0.5], hidden: true,
      icon: "Icon_CilinderSolid_grounded",
      model: "CylinderSolidGrounded", texture: "DefaultGreenMetal_Diffuse.png" },
    { type: "WallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.125], pivot: "center", rotationAxes: "y", floor: true, color: "#8B99A6",
      defaultScale: [2, 2.5, 1], icon: "Icon_WallSolid_1",
      model: "WallSolid", texture: "DefaultGreenMetal_Diffuse.png" },
    { type: "Crate", label: "Crate", category: "Props", shape: "crate", size: [0.5, 0.5, 0.5],
      pivot: "base", rotationAxes: "y", floor: true, color: "#9B8773", defaultScale: [1, 1, 1],
      icon: "Icon_Crate",
      model: "Crate", texture: "Crate_Diffuse.png" },
    { type: "DestructibleCrate", label: "Destructible Crate", category: "Props",
      shape: "crateDestructible", size: [0.5, 0.5, 0.5], pivot: "base", rotationAxes: "y",
      floor: true, color: "#A47768", defaultScale: [1, 1, 1], icon: "Icon_CrateDestructable",
      model: "DestructibleCrate", texture: "WoodenCrateBreakable_Diffuse.png" },
    { type: "DefaultElectricityBox", label: "Electricity Box", category: "Props",
      shape: "electricityBox", size: [0.545, 0.714, 0.44], pivot: "base", rotationAxes: "y",
      floor: true, color: "#719186", defaultScale: [1, 1, 1],
      icon: "Icon_ElectricityBoxDefault",
      model: "ElectricityBoxDefaultVisual", texture: "ElectricityBoxGreen_Diffuse.png" },
    ],
  },
  {
    id: "blue", name: "Blue", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "BlueBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#3E7BB8", defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierCornerBlueVisual", texture: "BarrierBlue_Diffuse.png", icon: "icon_DefaultBarrierCornerBlue" },
    { type: "BlueBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#3E7BB8", defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierFullBlueVisual", texture: "BarrierBlue_Diffuse.png", icon: "icon_DefaultBarrierFullBlue" },
    { type: "BlueBarrierLow", label: "Barrier Low", category: "Barriers", shape: "barrierLow",
      size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true, color: "#3E7BB8",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierLowBlueVisual", texture: "BarrierBlue_Diffuse.png", icon: "icon_DefaultBarrierLowBlue" },
    { type: "BlueBarrierU", label: "Barrier U", category: "Barriers", shape: "barrierU",
      size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true, color: "#3E7BB8",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierUBlueVisual", texture: "BarrierWindowBlue_Diffuse.png", icon: "icon_DefaultBarrierUBlue" },
    { type: "BlueBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#3E7BB8", defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierWindowBlueVisual", texture: "BarrierWindowBlue_Diffuse.png", icon: "icon_DefaultBarrierWindowBlue" },
    { type: "BlueTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#3E7BB8",
      defaultScale: [1, 2, 1], uncertain: true,
      model: "BlueTunnel", texture: "DefaultBlueMetal_Diffuse.png", icon: "icon_TunelBlue" },
    { type: "BlueBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#3E7BB8",
      defaultScale: [1, 1, 1],
      model: "BlueBoxSolid", texture: "DefaultBlueMetal_Diffuse.png", icon: "icon_CubeBlue" },
    { type: "BlueBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#3E7BB8", defaultScale: [1, 1, 1], hidden: true,
      model: "BlueBoxSolidGrounded", texture: "DefaultBlueMetal_Diffuse.png", icon: "icon_CubeBlue_grounded" },
    { type: "BlueCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#3E7BB8", defaultScale: [0.5, 2, 0.5],
      model: "BlueCylinderSolid", texture: "DefaultBlueMetal_Diffuse.png", icon: "icon_CilinderBlue" },
    { type: "BlueCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#3E7BB8", defaultScale: [0.5, 2, 0.5],
      hidden: true,
      model: "BlueCylinderSolidGrounded", texture: "DefaultBlueMetal_Diffuse.png", icon: "icon_CilinderBlue_grounded" },
    { type: "BlueWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#3E7BB8",
      defaultScale: [2, 2.5, 1], uncertain: true,
      model: "BlueWallSolid", texture: "DefaultBlueMetal_Diffuse.png", icon: "icon_WallBlue" },
    { type: "BlueCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#787A7C",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultCrateBlueVisual", texture: "BoxBlue_Diffuse.png", icon: "icon_DefaultCrateBlue" },
    { type: "BlueDestructibleCrate", label: "Destructible Crate", category: "Props",
      shape: "crateDestructible", size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y",
      floor: true, color: "#816A71", defaultScale: [1, 1, 1], uncertain: true,
      model: "BlueDestructibleCrate", texture: "WoodenCrateBreakableBlue.png", icon: "icon_DefaultCrateDestructableBlue" },
    { type: "BlueElectricityBox", label: "Electricity Box", category: "Props",
      shape: "electricityBox", size: [0.4, 0.6, 0.28], pivot: "base", rotationAxes: "y",
      floor: true, color: "#4F838E", defaultScale: [1, 1, 1], uncertain: true,
      model: "ElectricityBoxBlue", texture: "ElectricityBoxBlue_Diffuse.png", icon: "Icon_ElectricityBoxBlue" },
    ],
  },
  {
    id: "orange", name: "Orange", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "OrangeBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#D5822F", defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierCornerOrangeVisual", texture: "BarrierOrange_Diffuse.png", icon: "icon_DefaultBarrierCornerOrange" },
    { type: "OrangeBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#D5822F", defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierFullOrangeVisual", texture: "BarrierOrange_Diffuse.png", icon: "icon_DefaultBarrierFullOrange" },
    { type: "OrangeBarrierLow", label: "Barrier Low", category: "Barriers", shape: "barrierLow",
      size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true, color: "#D5822F",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierLowOrangeVisual", texture: "BarrierOrange_Diffuse.png", icon: "icon_DefaultBarrierLowOrange" },
    { type: "OrangeBarrierU", label: "Barrier U", category: "Barriers", shape: "barrierU",
      size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true, color: "#D5822F",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierUOrangeVisual", texture: "BarrierWindowOrange_Diffuse.png", icon: "icon_DefaultBarrierUOrange" },
    { type: "OrangeBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#D5822F", defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierWindowOrangeVisual", texture: "BarrierWindowOrange_Diffuse.png", icon: "icon_DefaultBarrierWindowOrange" },
    { type: "OrangeTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#D5822F",
      defaultScale: [1, 2, 1], uncertain: true,
      model: "OrangeTunnel", texture: "DefaultOrangeMetal_Diffuse.png", icon: "icon_TuneOrange" },
    { type: "OrangeBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#D5822F",
      defaultScale: [1, 1, 1],
      model: "OrangeBoxSolid", texture: "DefaultOrangeMetal_Diffuse.png", icon: "icon_CubeOrange" },
    { type: "OrangeBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#D5822F", defaultScale: [1, 1, 1], hidden: true,
      model: "OrangeBoxSolidGrounded", texture: "DefaultOrangeMetal_Diffuse.png", icon: "icon_CubeOrange_grounded" },
    { type: "OrangeCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#D5822F", defaultScale: [0.5, 2, 0.5],
      model: "OrangeCylinderSolid", texture: "DefaultOrangeMetal_Diffuse.png", icon: "icon_CilinderOrange" },
    { type: "OrangeCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#D5822F", defaultScale: [0.5, 2, 0.5],
      hidden: true,
      model: "OrangeCylinderSolidGrounded", texture: "DefaultOrangeMetal_Diffuse.png", icon: "icon_CilinderOrange_grounded" },
    { type: "OrangeWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#D5822F",
      defaultScale: [2, 2.5, 1], uncertain: true,
      model: "OrangeWallSolid", texture: "DefaultOrangeMetal_Diffuse.png", icon: "icon_WallOrange" },
    { type: "OrangeCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#BC7D3E",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultCrateOrangeVisual", texture: "BoxOrange_Diffuse.png", icon: "icon_DefaultCrateOrange" },
    { type: "OrangeDestructibleCrate", label: "Destructible Crate", category: "Props",
      shape: "crateDestructible", size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y",
      floor: true, color: "#C56D33", defaultScale: [1, 1, 1], uncertain: true,
      model: "OrangeDestructibleCrate", texture: "WoodenCrateBreakableOrange.png", icon: "icon_DefaultCrateDestructableOrange" },
    { type: "OrangeElectricityBox", label: "Electricity Box", category: "Props",
      shape: "electricityBox", size: [0.4, 0.6, 0.28], pivot: "base", rotationAxes: "y",
      floor: true, color: "#928650", defaultScale: [1, 1, 1], uncertain: true,
      model: "ElectricityBoxOrange", texture: "ElectricityBoxOrange.png", icon: "Icon_ElectricityBoxOrange" },
    ],
  },
  {
    id: "purple", name: "Purple", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "PurpleBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#7C5CB0", defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierCornerPurpleVisual", texture: "BarrierPurple_Diffuse.png", icon: "icon_DefaultBarrierCornerPurple" },
    { type: "PurpleBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#7C5CB0", defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierFullPurpleVisual", texture: "BarrierPurple_Diffuse.png", icon: "icon_DefaultBarrierFullPurple" },
    { type: "PurpleBarrierLow", label: "Barrier Low", category: "Barriers", shape: "barrierLow",
      size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true, color: "#7C5CB0",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierLowPurpleVisual", texture: "BarrierPurple_Diffuse.png", icon: "icon_DefaultBarrierLowPurple" },
    { type: "PurpleBarrierU", label: "Barrier U", category: "Barriers", shape: "barrierU",
      size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true, color: "#7C5CB0",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierUPurpleVisual", texture: "BarrierWindowPurple_Diffuse.png", icon: "icon_DefaultBarrierUPurple" },
    { type: "PurpleBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#7C5CB0", defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultBarrierWindowPurpleVisual", texture: "BarrierWindowPurple_Diffuse.png", icon: "icon_DefaultBarrierWindowPurple" },
    { type: "PurpleTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#7C5CB0",
      defaultScale: [1, 2, 1], uncertain: true,
      model: "PurpleTunnel", texture: "DefaultPurpleMetal_Diffuse.png", icon: "icon_TunePurple" },
    { type: "PurpleBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#7C5CB0",
      defaultScale: [1, 1, 1],
      model: "PurpleBoxSolid", texture: "DefaultPurpleMetal_Diffuse.png", icon: "icon_CubePurple" },
    { type: "PurpleBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#7C5CB0", defaultScale: [1, 1, 1], hidden: true,
      model: "PurpleBoxSolidGrounded", texture: "DefaultPurpleMetal_Diffuse.png", icon: "icon_CubePurple_grounded" },
    { type: "PurpleCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#7C5CB0", defaultScale: [0.5, 2, 0.5],
      model: "PurpleCylinderSolid", texture: "DefaultPurpleMetal_Diffuse.png", icon: "icon_CilinderPurple" },
    { type: "PurpleCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#7C5CB0", defaultScale: [0.5, 2, 0.5],
      hidden: true,
      model: "PurpleCylinderSolidGrounded", texture: "DefaultPurpleMetal_Diffuse.png", icon: "icon_CilinderPurple_grounded" },
    { type: "PurpleWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#7C5CB0",
      defaultScale: [2, 2.5, 1], uncertain: true,
      model: "PurpleWallSolid", texture: "DefaultPurpleMetal_Diffuse.png", icon: "icon_WallPurple" },
    { type: "PurpleCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#946C78",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "DefaultCratePurpleVisual", texture: "BoxPurple_Diffuse.png", icon: "icon_DefaultCratePurple" },
    { type: "PurpleDestructibleCrate", label: "Destructible Crate", category: "Props",
      shape: "crateDestructible", size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y",
      floor: true, color: "#9D5C6D", defaultScale: [1, 1, 1], uncertain: true,
      model: "PurpleDestructibleCrate", texture: "WoodenCrateBreakablePurple.png", icon: "icon_DefaultCrateDestructablePurple" },
    { type: "PurpleElectricityBox", label: "Electricity Box", category: "Props",
      shape: "electricityBox", size: [0.4, 0.6, 0.28], pivot: "base", rotationAxes: "y",
      floor: true, color: "#6A758A", defaultScale: [1, 1, 1], uncertain: true,
      model: "ElectricityBoxPurple", texture: "ElectricityBoxPurple_Diffuse.png", icon: "Icon_ElectricityBoxPurple" },
    ],
  },
  {
    id: "camo", name: "Camo", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "CamoBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#6E7A48", defaultScale: [1, 1, 1], uncertain: true,
      model: "CamoBarrier90CornerVisual", texture: "CamoBarrier_Diffuse.png", icon: "icon_MilitaryBarrier90Corner" },
    { type: "CamoBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#6E7A48", defaultScale: [1, 1, 1], uncertain: true,
      model: "CamoBarrierFullVisual", texture: "CamoBarrier_Diffuse.png", icon: "icon_MilitaryBarrierFull" },
    { type: "CamoBarrierLow", label: "Barrier Low", category: "Barriers", shape: "barrierLow",
      size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true, color: "#6E7A48",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "CamoBarrierHalfVisual", texture: "CamoBarrier_Diffuse.png", icon: "icon_MilitaryBarrierHalf" },
    { type: "CamoBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#6E7A48", defaultScale: [1, 1, 1], uncertain: true,
      model: "CamoBarrierWindowVisual", texture: "CamoBarrier_Diffuse.png", icon: "icon_MilitaryBarrierWindow" },
    { type: "CamoBarrierX", label: "Barrier X", category: "Barriers", shape: "barrierX",
      size: [1.4, 1.4, 1.4], pivot: "base", rotationAxes: "y", floor: true, color: "#6E7A48",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "CamoBarrierUVisual", texture: "CamoBarrier_Diffuse.png", icon: "icon_MilitaryBarrierU" },
    { type: "CamoTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#6E7A48",
      defaultScale: [1, 2, 1], uncertain: true,
      model: "CamoTunnel", texture: "CamoWall_Diffuse.png", icon: "icon_MilitaryTunel" },
    { type: "CamoBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#6E7A48",
      defaultScale: [1, 1, 1],
      model: "CamoBoxSolid", texture: "CamoWall_Diffuse.png", icon: "icon_MilitaryCube" },
    { type: "CamoBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#6E7A48", defaultScale: [1, 1, 1], hidden: true,
      model: "CamoBoxSolidGrounded", texture: "CamoWall_Diffuse.png", icon: "icon_MilitaryCube_grounded" },
    { type: "CamoCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#6E7A48", defaultScale: [0.5, 2, 0.5],
      model: "CamoCylinderSolid", texture: "CamoWall_Diffuse.png", icon: "icon_MilitaryCilinder" },
    { type: "CamoCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#6E7A48", defaultScale: [0.5, 2, 0.5],
      hidden: true,
      model: "CamoCylinderSolidGrounded", texture: "CamoWall_Diffuse.png", icon: "icon_MilitaryCilinder_grounded" },
    { type: "CamoWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#6E7A48",
      defaultScale: [2, 2.5, 1], uncertain: true,
      model: "CamoWallSolid", texture: "Trimsheet_basecolor.png", icon: "icon_MilitaryWall" },
    { type: "CamoCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#8E7949",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "CamoCrate", texture: "CamoCrateCombined_Diffuse.png", icon: "icon_MilitaryCrate" },
    { type: "CamoCrateBig", label: "Crate Big", category: "Props", shape: "crateBig",
      size: [0.9, 0.9, 0.9], pivot: "base", rotationAxes: "y", floor: true, color: "#8E7949",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "CamoCrateBig", texture: "CamoCrateCombined_Diffuse.png", icon: "icon_MilitaryCrateBig" },
    ],
  },
  {
    id: "mykea", name: "Mykea", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "MYKEABarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#C9A97A", defaultScale: [1, 1, 1], uncertain: true,
      model: "IndoorBarrierCornerVisual", texture: "IndoorBarrierCorner_Diffuse.png", icon: "Image_MYKEA_barrier_corner_icon" },
    { type: "MYKEABarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#C9A97A", defaultScale: [1, 1, 1], uncertain: true,
      model: "IndoorBarrierFullVisual", texture: "Mykea_Diffuse.png", icon: "Image_MYKEA_barrier_full_icon" },
    { type: "MYKEABarrierLow", label: "Barrier Low", category: "Barriers", shape: "barrierLow",
      size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true, color: "#C9A97A",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "IndoorBarrierLowVisual", texture: "Mykea_Diffuse.png", icon: "Image_MYKEA_barrier_low_icon" },
    { type: "MYKEABarrierU", label: "Barrier U", category: "Barriers", shape: "barrierU",
      size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true, color: "#C9A97A",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "IndoorBarrierUVisualCouch", texture: "MykeaObjects_Diffuse.png", icon: "Image_MYKEA_barrier_U_icon" },
    { type: "MYKEABarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#C9A97A", defaultScale: [1.2337, 1.2337, 1.2337], uncertain: true,
      model: "IndoorBarrierWindowVisual", texture: "Mykea_Diffuse.png", icon: "Image_MYKEA_barrier_window_icon" },
    { type: "MYKEATunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#C9A97A",
      defaultScale: [1, 2, 1], uncertain: true,
      model: "MYKEATunnel", texture: "IndoorPrimitives_Diffuse.png", icon: "Image_MYKEA_Tunel" },
    { type: "MYKEABoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#C9A97A",
      defaultScale: [1, 1, 1],
      model: "MYKEABoxSolid", texture: "IndoorPrimitives_Diffuse.png", icon: "Image_MYKEA_Solid_box" },
    { type: "MYKEABoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#C9A97A", defaultScale: [1, 1, 1], hidden: true,
      model: "MYKEABoxSolidGrounded", texture: "IndoorPrimitives_Diffuse.png", icon: "Image_MYKEA_Solid_box_grounded" },
    { type: "MYKEACylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#C9A97A", defaultScale: [0.5, 2, 0.5],
      model: "MYKEACylinderSolid", texture: "IndoorPrimitives_Diffuse.png", icon: "Image_MYKEA_Solid_cilinder" },
    { type: "MYKEACylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#C9A97A", defaultScale: [0.5, 2, 0.5],
      hidden: true,
      model: "MYKEACylinderSolidGrounded", texture: "IndoorPrimitives_Diffuse.png", icon: "Image_MYKEA_Solid_cilinder_grounded" },
    { type: "MYKEAWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#C9A97A",
      defaultScale: [2, 2.5, 1], uncertain: true,
      model: "MYKEAWallSolid", texture: "IndoorWoodWall_Diffuse.png", icon: "Image_MYKEA_Wall" },
    { type: "MYKEACushion", label: "Cushion", category: "Props", shape: "cushion",
      size: [0.5, 0.18, 0.5], pivot: "base", rotationAxes: "y", floor: true, color: "#CDA77C",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "IndoorBarrierCrateVisual", texture: "MikeaPillow_Diffuse.png", icon: "Image_MYKEA_crate_icon" },
    { type: "MYKEAOttoman", label: "Ottoman", category: "Props", shape: "ottoman",
      size: [0.6, 0.42, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#C49868",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "IndoorCover1x1", texture: "MikeaPillow_Diffuse.png", icon: "Image_MYKEA_cover_icon" },
    { type: "MYKEASofa", label: "Sofa", category: "Props", shape: "sofa",
      size: [1.6, 0.78, 0.82], pivot: "base", rotationAxes: "y", floor: true, color: "#C49868",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "IndoorBarrierGroundedVisualCouch", icon: "Image_MYKEA_sofa_icon" },
    ],
  },
  {
    id: "graffiti", name: "Graffiti", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "GraffitiBarrierBroken", label: "Barrier Broken", category: "Barriers",
      shape: "barrierBroken", size: [1, 1.1, 0.16], pivot: "base", rotationAxes: "y",
      floor: true, color: "#7F8B97", defaultScale: [1, 1, 1], uncertain: true,
      model: "BarrierStreetStyleBroken2x1m", texture: "GraffitiBarrier_Diffuse.png", icon: "icon_Grafitti_LBarrier" },
    { type: "GraffitiBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#7F8B97", defaultScale: [1, 1, 1], uncertain: true,
      model: "BarrierStreetStyleCorner90", texture: "GraffitiBarrier_Diffuse.png", icon: "icon_Grafitti_CornerBarrier" },
    { type: "GraffitiBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#7F8B97", defaultScale: [1, 1, 1], uncertain: true,
      model: "BarrierStreetStyle2x1", texture: "GraffitiBarrier_Diffuse.png", icon: "icon_Grafitti_Barrier" },
    { type: "GraffitiBarrierLow", label: "Barrier Low", category: "Barriers",
      shape: "barrierLow", size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#7F8B97", defaultScale: [1, 1, 1], uncertain: true,
      model: "BarrierStreetStyleLow1m", texture: "GraffitiBarrier_Diffuse.png", icon: "icon_Grafitti_ShortBarrier" },
    { type: "GraffitiBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#7F8B97", defaultScale: [1, 1, 1], uncertain: true,
      model: "BarrierStreetStyleWindow2x1m", texture: "GraffitiBarrier_Diffuse.png", icon: "icon_Grafitti_WindowBarrier" },
    { type: "GraffitiTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#7F8B97",
      defaultScale: [1, 2, 1], uncertain: true,
      model: "GraffitiTunnel", texture: "Graffiti_Diffuse.png", icon: "icon_Grafitti_Tunel" },
    { type: "GraffitiBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#7F8B97",
      defaultScale: [1, 1, 1],
      model: "GraffitiBoxSolid", texture: "Graffiti_Diffuse.png", icon: "icon_Grafitti_Box_crate" },
    { type: "GraffitiBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#7F8B97", defaultScale: [1, 1, 1], hidden: true,
      model: "GraffitiBoxSolidGrounded", texture: "Graffiti_Diffuse.png", icon: "icon_Grafitti_Box_crate_grounded" },
    { type: "GraffitiCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#7F8B97", defaultScale: [0.5, 2, 0.5],
      model: "GraffitiCylinderSolid", texture: "Graffiti_Diffuse.png", icon: "icon_Grafitti_Cilinder_crate" },
    { type: "GraffitiCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#7F8B97", defaultScale: [0.5, 2, 0.5],
      hidden: true,
      model: "GraffitiCylinderSolidGrounded", texture: "Graffiti_Diffuse.png", icon: "icon_Grafitti_Cilinder_crate_grounded" },
    { type: "GraffitiWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#7F8B97",
      defaultScale: [2, 2.5, 1], uncertain: true,
      model: "GraffitiWallSolid", texture: "Trimsheet_basecolor.png", icon: "icon_Grafitti_Wall" },
    { type: "GraffitiBarrel", label: "Barrel", category: "Props", shape: "barrel",
      size: [0.56, 0.86, 0.56], pivot: "base", rotationAxes: "y", floor: true, color: "#857965",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "StreetStyleBarrel", texture: "StreetStyleBarrelCrate_Diffuse.png", icon: "icon_Grafitti_Barrel" },
    { type: "GraffitiCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#96816D",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "StreetStyleCrate", texture: "StreetStyleBarrelCrate_Diffuse.png", icon: "icon_Grafitti_Crate" },
    { type: "GraffitiPigeon", label: "Pigeon", category: "Props", shape: "pigeon",
      size: [0.18, 0.26, 0.34], pivot: "base", rotationAxes: "y", floor: true, color: "#8C98A4",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "StreetStylePigeon", icon: "icon_Grafitti_Pidgeon" },
    ],
  },
  {
    id: "paintball", name: "Paintball", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "PaintballBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#34A57C", defaultScale: [1, 1, 1], uncertain: true,
      model: "PaintBallBarrierCornerVisual", texture: "PaintBarrierX2x1_Diffuse.png", icon: "icon_PaintBallBarrierCorner" },
    { type: "PaintballBarrierD", label: "Barrier D", category: "Barriers", shape: "barrierD",
      size: [1.2, 1.4, 0.9], pivot: "base", rotationAxes: "y", floor: true, color: "#34A57C",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "PaintBallBarrierUVisual", texture: "PaintBarrierU2x1_Diffuse.png", icon: "icon_PaintBallBarrierU" },
    { type: "PaintballBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#34A57C", defaultScale: [1, 1, 1], uncertain: true,
      model: "PaintBallBarrierFullVisual", texture: "PaintBallBarrier2x1_Diffuse.png", icon: "icon_PaintBallBarrierFull" },
    { type: "PaintballBarrierLow", label: "Barrier Low", category: "Barriers",
      shape: "barrierLow", size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#34A57C", defaultScale: [1, 1, 1], uncertain: true,
      model: "PaintBallBarrierLowVisual", texture: "PaintBallBarrier_Diffuse.png", icon: "icon_PaintBallBarrierLow" },
    { type: "PaintballBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#34A57C", defaultScale: [1, 1, 1], uncertain: true,
      model: "PaintBallBarrierWindowVisual", texture: "PaintBallBarrier_Diffuse.png", icon: "icon_PaintBallBarrierWindow" },
    { type: "PaintballTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#34A57C",
      defaultScale: [1, 2, 1], uncertain: true,
      model: "PaintBallTunnel", texture: "Chipboard_basecolor.png", icon: "icon_PaintBallSolidTunel" },
    { type: "PaintballBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#34A57C",
      defaultScale: [1, 1, 1],
      model: "PaintBallBoxSolid", texture: "Chipboard_basecolor.png", icon: "icon_PaintBallSolidCrate" },
    { type: "PaintballBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#34A57C", defaultScale: [1, 1, 1], hidden: true,
      model: "PaintBallBoxSolidGrounded", texture: "Chipboard_basecolor.png", icon: "icon_PaintBallSolidCrate_grounded" },
    { type: "PaintballCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#34A57C", defaultScale: [0.5, 2, 0.5],
      model: "PaintBallCylinderSolid", texture: "Chipboard_basecolor.png", icon: "icon_PaintBallSolidCilinder" },
    { type: "PaintballCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#34A57C", defaultScale: [0.5, 2, 0.5],
      hidden: true,
      model: "PaintBallCylinderSolidGrounded", texture: "Chipboard_basecolor.png", icon: "icon_PaintBallSolidCilinder_grounded" },
    { type: "PaintballWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#34A57C",
      defaultScale: [2, 2.5, 1], uncertain: true,
      model: "PaintBallWallSolid", texture: "PaintBallWall_Diffuse.png", icon: "icon_PaintBallSolidWall" },
    { type: "PaintballCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#748D61",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "PaintBallCrateVisual", texture: "PaintBallCover1x1_Diffuse.png", icon: "icon_PaintBallCrate" },
    ],
  },
  {
    id: "wildwest", name: "Wild West", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "WildWestBarrierBroken", label: "Barrier Broken", category: "Barriers",
      shape: "barrierBroken", size: [1, 1.1, 0.16], pivot: "base", rotationAxes: "y",
      floor: true, color: "#9E7346", defaultScale: [1, 1, 1], uncertain: true,
      model: "WildWestBarrierBroken", texture: "WildWestBarrier01_Diffuse.png", icon: "Image_WildWest_barrier_broken_icon" },
    { type: "WildWestBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#9E7346", defaultScale: [1, 1, 1], uncertain: true,
      model: "WildWestBarrierCorner90", texture: "WildWestBarrier02_Diffuse.png", icon: "Image_WildWest_barrier_corner_icon" },
    { type: "WildWestBarrierDoor", label: "Barrier Door", category: "Barriers",
      shape: "barrierDoor", size: [1.1, 1.3, 0.16], pivot: "base", rotationAxes: "y",
      floor: true, color: "#9E7346", defaultScale: [1, 1, 1], uncertain: true,
      model: "WildWestBarrierDoor", texture: "WildWestBarrier01_Diffuse.png", icon: "Image_WildWest_barrier_door_icon" },
    { type: "WildWestBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#9E7346", defaultScale: [1, 1, 1], uncertain: true,
      model: "WildWestBarrierTall", texture: "WildWestBarrier02_Diffuse.png", icon: "Image_WildWest_barrier_full_icon" },
    { type: "WildWestBarrierLow", label: "Barrier Low", category: "Barriers",
      shape: "barrierLow", size: [1, 0.6, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#9E7346", defaultScale: [1, 1, 1], uncertain: true,
      model: "WildWestBarrierShort", texture: "WildWestBarrier02_Diffuse.png", icon: "Image_WildWest_barrier_short_icon" },
    { type: "WildWestTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#9E7346",
      defaultScale: [1, 2, 1], uncertain: true,
      model: "WildWestTunnel", texture: "WildWestWood_Diffuse.png", icon: "Image_WildWest_tunel" },
    { type: "WildWestBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#9E7346",
      defaultScale: [1, 1, 1],
      model: "WildWestBoxSolid", texture: "WildWestWood_Diffuse.png", icon: "Image_WildWest_cube" },
    { type: "WildWestBoxSolidGrounded", label: "Solid Box (Grounded)", category: "Primitives",
      shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true,
      color: "#9E7346", defaultScale: [1, 1, 1], hidden: true,
      model: "WildWestBoxSolidGrounded", texture: "WildWestWood_Diffuse.png", icon: "Image_WildWest_cube_grounded" },
    { type: "WildWestCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#9E7346", defaultScale: [0.5, 2, 0.5],
      model: "WildWestCylinderSolid", texture: "WildWestWood_Diffuse.png", icon: "Image_WildWest_cilinder" },
    { type: "WildWestCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#9E7346", defaultScale: [0.5, 2, 0.5],
      hidden: true,
      model: "WildWestCylinderSolidGrounded", texture: "WildWestWood_Diffuse.png", icon: "Image_WildWest_cilinder_grounded" },
    { type: "WildWestWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#9E7346",
      defaultScale: [2, 2.5, 1], uncertain: true,
      model: "WildWestWallSolid", texture: "WildWestWood_Diffuse.png", icon: "Image_WildWest_wall" },
    { type: "WildWestBarrel", label: "Barrel", category: "Props", shape: "barrel",
      size: [0.56, 0.86, 0.56], pivot: "base", rotationAxes: "y", floor: true, color: "#936E41",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "WildWestBarrel", texture: "WildWestCactiBarrel_Diffuse.png", icon: "Image_WildWest_barrel_icon" },
    { type: "WildWestCacti", label: "Cacti", category: "Props", shape: "cacti",
      size: [0.7, 1.5, 0.5], pivot: "base", rotationAxes: "y", floor: true, color: "#7B804D",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "WildWestCacti", texture: "WildWestCactiBarrel_Diffuse.png", icon: "Image_WildWest_barrier_cactus_icon" },
    ],
  },
  {
    id: "hatchetcorp", name: "Hatchet Corp", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "HatchetCorpBarrierCorner", label: "Barrier Corner", category: "Barriers",
      shape: "barrierCorner", size: [1, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true,
      color: "#6B7784", defaultScale: [1, 1, 1], uncertain: true,
      model: "HatCoBarrierCornerVisual", texture: "HatCoBarriersTextureUpdated_Diffuse.png", icon: "icon_HatCoBarrierCorner" },
    { type: "HatchetCorpBarrierDoorway", label: "Barrier Doorway", category: "Barriers",
      shape: "barrierDoorway", size: [1.4, 2.1, 0.16], pivot: "base", rotationAxes: "y",
      floor: true, color: "#6B7784", defaultScale: [1, 1, 1], uncertain: true,
      model: "HatCoBarrierDoorwayVisual", texture: "HatCoBarriersTextureUpdated_Diffuse.png", icon: "icon_HatCoBarrierDoorway" },
    { type: "HatchetCorpBarrierFull", label: "Barrier Full", category: "Barriers",
      shape: "barrierFull", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y", floor: true,
      color: "#6B7784", defaultScale: [1, 1, 1], uncertain: true,
      model: "HatCoBarrierFullVisual", texture: "HatCoBarriersTextureUpdated_Diffuse.png", icon: "icon_HatCoBarrierSmallWindow" },
    { type: "HatchetCorpBarrierL", label: "Barrier L", category: "Barriers", shape: "barrierL",
      size: [1.4, 1.4, 1], pivot: "base", rotationAxes: "y", floor: true, color: "#6B7784",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "HatCoBarrierUVisual", texture: "HatCoBarriersTextureUpdated_Diffuse.png", icon: "icon_HatCoBarrierU" },
    { type: "HatchetCorpBarrierSlope", label: "Barrier Slope", category: "Barriers",
      shape: "barrierSlope", size: [1, 1, 1.2], pivot: "base", rotationAxes: "y", floor: true,
      color: "#6B7784", defaultScale: [1, 1, 1], uncertain: true,
      model: "HatCoBarrierSlopeVisual", texture: "HatCoBarriersTextureUpdated_Diffuse.png", icon: "icon_HatCoBarrierSlope" },
    { type: "HatchetCorpBarrierWindow", label: "Barrier Window", category: "Barriers",
      shape: "barrierWindow", size: [1, 1.4, 0.14], pivot: "base", rotationAxes: "y",
      floor: true, color: "#6B7784", defaultScale: [1, 1, 1], uncertain: true,
      model: "HatCoBarrierWallWindow", texture: "HatCoBarriersTextureUpdated_Diffuse.png", icon: "icon_HatCoBarrierWallWindow" },
    { type: "HatchetCorpPillar", label: "Pillar", category: "Structures", shape: "pillar",
      size: [0.5, 2.4, 0.5], pivot: "base", rotationAxes: "y", floor: true, color: "#6B7784",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "HatCoBarrierPillarVisual", texture: "HatCoBarriersTextureUpdated_Diffuse.png", icon: "icon_HatCoBarrierPillar" },
    { type: "HatchetCorpTunnel", label: "Tunnel", category: "Structures", shape: "tunnel",
      size: [1, 1, 1], pivot: "center", rotationAxes: "y", floor: true, color: "#6B7784",
      defaultScale: [1, 2, 1], uncertain: true,
      model: "HatchetCorpTunnel", texture: "HatchetCorpWall_Diffuse.png", icon: "icon_HatCoTunel" },
    { type: "HatchetCorpBoxSolid", label: "Solid Box", category: "Primitives", shape: "box",
      size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false, color: "#6B7784",
      defaultScale: [1, 1, 1],
      model: "HatchetCorpBoxSolid", texture: "HatchetCorpWall_Diffuse.png", icon: "icon_HatCoBoxSolid" },
    { type: "HatchetCorpBoxSolidGrounded", label: "Solid Box (Grounded)",
      category: "Primitives", shape: "box", size: [1, 1, 1], pivot: "center", rotationAxes: "y",
      floor: true, color: "#6B7784", defaultScale: [1, 1, 1], hidden: true,
      model: "HatchetCorpBoxSolidGrounded", texture: "HatchetCorpWall_Diffuse.png", icon: "icon_HatCoBoxSolid_grounded" },
    { type: "HatchetCorpCylinderSolid", label: "Solid Cylinder", category: "Primitives",
      shape: "cylinder", size: [1, 1, 1], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#6B7784", defaultScale: [0.5, 2, 0.5],
      model: "HatchetCorpCylinderSolid", texture: "HatchetCorpWall_Diffuse.png", icon: "icon_HatCoCilinderSolid" },
    { type: "HatchetCorpCylinderSolidGrounded", label: "Solid Cylinder (Grounded)",
      category: "Primitives", shape: "cylinder", size: [1, 1, 1], pivot: "center",
      rotationAxes: "y", floor: true, color: "#6B7784", defaultScale: [0.5, 2, 0.5],
      hidden: true,
      model: "HatchetCorpCylinderSolidGrounded", texture: "HatchetCorpWall_Diffuse.png", icon: "icon_HatCoCilinderSolid_grounded" },
    { type: "HatchetCorpWallSolid", label: "Solid Wall", category: "Primitives", shape: "wall",
      size: [1, 1, 0.1], pivot: "center", rotationAxes: "y", floor: true, color: "#6B7784",
      defaultScale: [2, 2.5, 1], uncertain: true,
      model: "HatchetCorpWallSolid", texture: "HatchetCorpWall_Diffuse.png", icon: "icon_HatCoWall" },
    { type: "HatchetCorpCrate", label: "Crate", category: "Props", shape: "crate",
      size: [0.6, 0.6, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#8D7864",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "HatCoBarrierCrateVisual", texture: "HatCoBarrierCrate_Diffuse.png", icon: "icon_HatCoBarrierCrate" },
    ],
  },
  {
    id: "corrupted", name: "Corrupted Technology", group: "virtual", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "CenterStationCPU", label: "Center Station CPU", category: "Machines",
      shape: "centerStationCpu", size: [1.2, 1.6, 1.2], pivot: "base", rotationAxes: "y",
      floor: true, color: "#56708C", defaultScale: [1, 1, 1], uncertain: true,
      model: "CentralStationCPU", texture: "CenterStationCPUArena_Diffuse.png", icon: "Icon_Campaign_CenterStationCPU" },
    { type: "CoffeeMachine", label: "Coffee Machine", category: "Machines",
      shape: "coffeeMachine", size: [0.5, 1.4, 0.5], pivot: "base", rotationAxes: "y",
      floor: true, color: "#56708C", defaultScale: [1, 1, 1], uncertain: true,
      model: "CoffeeMachine", texture: "CoffeeMachineArena_Diffuse.png", icon: "Icon_Campaign_CoffeeMachine" },
    { type: "Console", label: "Console", category: "Machines", shape: "console",
      size: [1.1, 1.1, 0.6], pivot: "base", rotationAxes: "y", floor: true, color: "#56708C",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "Console", texture: "ConsoleArena_Diffuse.png", icon: "Icon_Campaign_Console" },
    { type: "Recuperator", label: "Recuperator", category: "Machines", shape: "recuperator",
      size: [1, 1.8, 1], pivot: "base", rotationAxes: "y", floor: true, color: "#56708C",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "Recuperator", texture: "RecuperatorArena_Diffuse.png", icon: "Icon_Campaign_Recuperator" },
    { type: "SampleAnalysisMachine", label: "Sample Analysis Machine", category: "Machines",
      shape: "sampleAnalysis", size: [1.2, 1.7, 0.8], pivot: "base", rotationAxes: "y",
      floor: true, color: "#56708C", defaultScale: [1, 1, 1], uncertain: true,
      model: "SampleAnalysisMachineArena", texture: "SampleAnalysisMachine_Diffuse.png", icon: "Icon_Campaign_SampleAnalysisMachine" },
    { type: "Server", label: "Server", category: "Machines", shape: "server",
      size: [0.7, 1.9, 0.9], pivot: "base", rotationAxes: "y", floor: true, color: "#56708C",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "Server", texture: "ServerArena_Diffuse.png", icon: "Icon_Campaign_Server" },
    { type: "WireContainer", label: "Wire Container", category: "Machines",
      shape: "wireContainer", size: [1, 1.1, 0.7], pivot: "base", rotationAxes: "y",
      floor: true, color: "#56708C", defaultScale: [1, 1, 1], uncertain: true,
      model: "WireContainer", texture: "WireContainerArena_Diffuse.png", icon: "Icon_Campaign_WireContainer" },
    { type: "Chopper", label: "Chopper", category: "Vehicles", shape: "chopper",
      size: [3.4, 2.6, 5.2], pivot: "base", rotationAxes: "y", floor: true, color: "#56708C",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "Chopper", texture: "ChopperArena_Diffuse.png", icon: "Icon_Campaign_Chopper" },
    { type: "Tank", label: "Tank", category: "Vehicles", shape: "tank", size: [2.8, 2.2, 5],
      pivot: "base", rotationAxes: "y", floor: true, color: "#56708C", defaultScale: [1, 1, 1],
      uncertain: true,
      model: "Tank", texture: "TankArena_Diffuse.png", icon: "Icon_Campaign_Tank" },
    { type: "Truck", label: "Truck", category: "Vehicles", shape: "truck", size: [2.2, 2.5, 5],
      pivot: "base", rotationAxes: "y", floor: true, color: "#56708C", defaultScale: [1, 1, 1],
      uncertain: true,
      model: "Truck", texture: "TruckArena_Diffuse.png", icon: "Icon_Campaign_Truck" },
    { type: "CrystalCircle", label: "Crystal Circle", category: "Crystals",
      shape: "crystalCircle", size: [1.2, 1.5, 1.2], pivot: "base", rotationAxes: "y",
      floor: true, color: "#7C76BA", defaultScale: [1, 1, 1], uncertain: true,
      model: "Crystal02", texture: "CrystalsArena_Emissive.png", icon: "Icon_Campaign_Crystal02" },
    { type: "CrystalHalfCircle", label: "Crystal Half Circle", category: "Crystals",
      shape: "crystalHalf", size: [1.2, 1.4, 0.7], pivot: "base", rotationAxes: "y",
      floor: true, color: "#7C76BA", defaultScale: [1, 1, 1], uncertain: true,
      model: "Crystal01", texture: "CrystalsArena_Emissive.png", icon: "Icon_Campaign_Crystal01" },
    { type: "CrystalSmall", label: "Crystal Small", category: "Crystals", shape: "crystalSmall",
      size: [0.7, 1.1, 0.7], pivot: "base", rotationAxes: "y", floor: true, color: "#7C76BA",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "Crystal03", texture: "CrystalsArena_Emissive.png", icon: "Icon_Campaign_Crystal03" },
    { type: "DarkCrystalCircle", label: "Dark Crystal Circle", category: "Crystals",
      shape: "crystalCircle", size: [1.2, 1.5, 1.2], pivot: "base", rotationAxes: "y",
      floor: true, color: "#595B89", defaultScale: [0.9195, 0.9195, 0.9195], uncertain: true,
      model: "CrystalDark02", texture: "DarkCrystalsArena_Emissive.png", icon: "Icon_Campaign_CrystalDark02" },
    { type: "DarkCrystalHalfCircle", label: "Dark Crystal Half Circle", category: "Crystals",
      shape: "crystalHalf", size: [1.2, 1.4, 0.7], pivot: "base", rotationAxes: "y",
      floor: true, color: "#595B89", defaultScale: [1, 1, 1], uncertain: true,
      model: "CrystalDark01", texture: "DarkCrystalsArena_Emissive.png", icon: "Icon_Campaign_CrystalDark01" },
    { type: "DarkCrystalSmall", label: "Dark Crystal Small", category: "Crystals",
      shape: "crystalSmall", size: [0.7, 1.1, 0.7], pivot: "base", rotationAxes: "y",
      floor: true, color: "#595B89", defaultScale: [1, 1, 1], uncertain: true,
      model: "CrystalDark03", texture: "DarkCrystalsArena_Emissive.png", icon: "Icon_Campaign_CrystalDark03" },
    ],
  },
  {
    id: "gameplay", name: "Gameplay Objects", group: "gameplay", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:All", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "All" }, label: "Any Weapon", category: "Weapon Spawns",
      shape: "spawnAll", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y", floor: true,
      color: "#E8C547", defaultScale: [1, 1, 1], uncertain: true,
      model: "WeaponSpawnPoint", texture: "initialShadingGroup_Diffuse.png", icon: "icon_gears_weaponspawner" },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:Flashbang",
      objectType: "WeaponSpawnPoint", props: { specificWeapon: "Flashbang" },
      label: "Flashbang", category: "Weapon Spawns", shape: "spawnFlashbang",
      size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y", floor: true, color: "#D8C77A",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "WeaponSpawnPoint", texture: "initialShadingGroup_Diffuse.png", icon: "Icon_flashbang_silhouette" },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:Grenade", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "Grenade" }, label: "Grenade", category: "Weapon Spawns",
      shape: "spawnGrenade", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y",
      floor: true, color: "#7FB77E", defaultScale: [1, 1, 1], uncertain: true,
      model: "WeaponSpawnPoint", texture: "initialShadingGroup_Diffuse.png", icon: "Icon_granade_silhouette" },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:Handgun", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "Handgun" }, label: "Handgun", category: "Weapon Spawns",
      shape: "spawnHandgun", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y",
      floor: true, color: "#4EC9E0", defaultScale: [1, 1, 1], uncertain: true,
      model: "WeaponSpawnPoint", texture: "initialShadingGroup_Diffuse.png", icon: "Icon_handgun_silhouette" },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:Healthpack",
      objectType: "WeaponSpawnPoint", props: { specificWeapon: "Healthpack" },
      label: "Health Pack", category: "Weapon Spawns", shape: "spawnHealthpack",
      size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y", floor: true, color: "#5AD6A0",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "WeaponSpawnPoint", texture: "initialShadingGroup_Diffuse.png", icon: "Icon_healthpack_silhouette" },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:RiotShield",
      objectType: "WeaponSpawnPoint", props: { specificWeapon: "RiotShield" },
      label: "Riot Shield", category: "Weapon Spawns", shape: "spawnRiotShield",
      size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y", floor: true, color: "#9AA7B4",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "WeaponSpawnPoint", texture: "initialShadingGroup_Diffuse.png", icon: "Icon_shield_silhouette" },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:RPG", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "RPG" }, label: "RPG", category: "Weapon Spawns",
      shape: "spawnRpg", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y", floor: true,
      color: "#4EC9E0", defaultScale: [1, 1, 1], uncertain: true,
      model: "WeaponSpawnPoint", texture: "initialShadingGroup_Diffuse.png", icon: "Icon_rpg_silhouette" },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:Shotgun", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "Shotgun" }, label: "Shotgun", category: "Weapon Spawns",
      shape: "spawnShotgun", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y",
      floor: true, color: "#4EC9E0", defaultScale: [1, 1, 1], uncertain: true,
      model: "WeaponSpawnPoint", texture: "initialShadingGroup_Diffuse.png", icon: "Icon_shotgun_silhouette" },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:SMG", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "SMG" }, label: "SMG", category: "Weapon Spawns",
      shape: "spawnSmg", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y", floor: true,
      color: "#4EC9E0", defaultScale: [1, 1, 1], uncertain: true,
      model: "WeaponSpawnPoint", texture: "initialShadingGroup_Diffuse.png", icon: "Icon_smg_silhouette" },
    { type: "WeaponSpawnPoint", key: "WeaponSpawnPoint:Sniper", objectType: "WeaponSpawnPoint",
      props: { specificWeapon: "Sniper" }, label: "Sniper", category: "Weapon Spawns",
      shape: "spawnSniper", size: [0.46, 0.5, 0.46], pivot: "base", rotationAxes: "y",
      floor: true, color: "#4EC9E0", defaultScale: [1, 1, 1], uncertain: true,
      model: "WeaponSpawnPoint", texture: "initialShadingGroup_Diffuse.png", icon: "Icon_sniper_silhouette" },
    { type: "DamageBox", objectType: "DamageBox", props: { style: "Red" }, label: "Damage Box",
      category: "Hazards", shape: "damageBox", size: [1, 1, 1], pivot: "center",
      rotationAxes: "xyz", floor: false, color: "#E0574B", defaultScale: [1, 1, 1],
      uncertain: true,
      model: "DamageBox", icon: "Icon_DamageBox" },
    { type: "DamageBoxTeam1", objectType: "DamageBox", props: { style: "Blue" },
      label: "Damage Box Team 1", category: "Hazards", shape: "damageBox", size: [1, 1, 1],
      pivot: "center", rotationAxes: "xyz", floor: false, color: "#4A90D9",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "DamageBoxTeam1", icon: "Icon_DamageBoxTeam1" },
    { type: "DamageBoxTeam2", objectType: "DamageBox", props: { style: "Orange" },
      label: "Damage Box Team 2", category: "Hazards", shape: "damageBox", size: [1, 1, 1],
      pivot: "center", rotationAxes: "xyz", floor: false, color: "#E08A3C",
      defaultScale: [1, 1, 1], uncertain: true,
      model: "DamageBoxTeam2", icon: "Icon_DamageBoxTeam2" },
    { type: "ExplosiveBarrel", label: "Explosive Barrel", category: "Hazards",
      shape: "explosiveBarrel", size: [0.56, 0.86, 0.56], pivot: "base", rotationAxes: "y",
      floor: true, color: "#C4452F", defaultScale: [1, 1, 1], uncertain: true,
      model: "ExplosiveBarrel", texture: "ExplosiveBarrel_Diffuse.png", icon: "Icon_ExplosiveBarrel" },
    { type: "Jumbotron", label: "Jumbotron", category: "Emplacements", shape: "jumbotron",
      size: [1.4, 0.9, 0.22], pivot: "center", rotationAxes: "xyz", floor: false,
      color: "#3A4C5A", defaultScale: [1, 1, 1], uncertain: true,
      model: "Jumbotron", icon: "Icon_JumbotronSingleScreen" },
    { type: "Minigun", label: "Minigun", category: "Emplacements", shape: "minigun",
      size: [0.8, 1.3, 0.9], pivot: "base", rotationAxes: "y", floor: true, color: "#6E7C8A",
      defaultScale: [0.9, 0.9, 0.9], uncertain: true,
      model: "Minigun", texture: "lambert1_Diffuse_0.png", icon: "Icon_Minigun" },
    ],
  },
  {
    id: "objectives", name: "Mode Objectives", group: "objectives", schema: PACK_SCHEMA_VERSION,
    objects: [
    { type: "PlayerSpawnZoneTeam1", label: "Player Spawn Zone Team 1", category: "Spawn Zones",
      shape: "spawnZone", size: [1.4, 1, 1.4], pivot: "base", rotationAxes: "y", floor: true,
      color: "#4A90D9", defaultScale: [1, 1, 1], uncertain: true,
      model: "PlayerSpawnZoneTeam1", texture: "TPgradientVerticalConcave00 1.png", icon: "Icon_SpawnZoneTeam1" },
    { type: "PlayerSpawnZoneTeam2", label: "Player Spawn Zone Team 2", category: "Spawn Zones",
      shape: "spawnZone", size: [1.4, 1, 1.4], pivot: "base", rotationAxes: "y", floor: true,
      color: "#E08A3C", defaultScale: [1, 1, 1], uncertain: true,
      model: "PlayerSpawnZoneTeam2", texture: "TPgradientVerticalConcave00 1.png", icon: "Icon_SpawnZoneTeam2" },
    { type: "EnemySpawnPoint", key: "EnemySpawnPoint:Default", objectType: "EnemySpawnPoint",
      props: { enemyTypes: "All", behaviour: "Default" }, label: "Enemy Spawn",
      category: "Enemy Spawns", shape: "enemySpawn", size: [0.7, 1.1, 0.7], pivot: "base",
      rotationAxes: "y", floor: true, color: "#C0553F", defaultScale: [1, 1, 1],
      uncertain: true,
      model: "EnemySpawnPoint", texture: "EnemySpawner_Diffuse.png", icon: "Icon_Enemy_Spawner" },
    { type: "EnemySpawnPoint", key: "EnemySpawnPoint:Aggresive", objectType: "EnemySpawnPoint",
      props: { enemyTypes: "All", behaviour: "Aggresive" }, label: "Enemy Spawn (Aggresive)",
      category: "Enemy Spawns", shape: "enemySpawn", size: [0.7, 1.1, 0.7], pivot: "base",
      rotationAxes: "y", floor: true, color: "#E0574B", defaultScale: [1, 1, 1],
      uncertain: true,
      model: "EnemySpawnPoint", texture: "EnemySpawner_Diffuse.png", icon: "Icon_Enemy_Spawner" },
    { type: "EnemySpawnPoint", key: "EnemySpawnPoint:Stationary", objectType: "EnemySpawnPoint",
      props: { enemyTypes: "All", behaviour: "Stationary" }, label: "Enemy Spawn (Stationary)",
      category: "Enemy Spawns", shape: "enemySpawn", size: [0.7, 1.1, 0.7], pivot: "base",
      rotationAxes: "y", floor: true, color: "#8A6A5A", defaultScale: [1, 1, 1],
      uncertain: true,
      model: "EnemySpawnPoint", texture: "EnemySpawner_Diffuse.png", icon: "Icon_Enemy_Spawner" },
    { type: "DominationZoneA", label: "Domination Zone A", category: "Domination",
      shape: "dominationZoneA", size: [1.5, 1, 1.5], pivot: "base", rotationAxes: "y",
      floor: true, color: "#E8C547", defaultScale: [1, 1, 1], uncertain: true,
      model: "DominationZoneA", texture: "Circle Outline 1024px - Stroke 10px.png", icon: "Icon_FlagA" },
    { type: "DominationZoneB", label: "Domination Zone B", category: "Domination",
      shape: "dominationZoneB", size: [1.5, 1, 1.5], pivot: "base", rotationAxes: "y",
      floor: true, color: "#B98FD6", defaultScale: [1, 1, 1], uncertain: true,
      model: "DominationZoneB", texture: "Circle Outline 1024px - Stroke 10px.png", icon: "Icon_FlagB" },
    { type: "DominationZoneC", label: "Domination Zone C", category: "Domination",
      shape: "dominationZoneC", size: [1.5, 1, 1.5], pivot: "base", rotationAxes: "y",
      floor: true, color: "#5AD6A0", defaultScale: [1, 1, 1], uncertain: true,
      model: "DominationZoneC", texture: "Circle Outline 1024px - Stroke 10px.png", icon: "Icon_FlagC" },
    { type: "CaptureFlagSpawnTeam1", label: "Capture Flag Spawn Team 1",
      category: "Capture The Flag", shape: "flagSpawn", size: [0.6, 1.8, 0.6], pivot: "base",
      rotationAxes: "y", floor: true, color: "#4A90D9", defaultScale: [1, 1, 1],
      uncertain: true,
      model: "CaptureFlagSpawnPointTeam1", icon: "Icon_OrangeTeamFlag" },
    { type: "CaptureFlagSpawnTeam2", label: "Capture Flag Spawn Team 2",
      category: "Capture The Flag", shape: "flagSpawn", size: [0.6, 1.8, 0.6], pivot: "base",
      rotationAxes: "y", floor: true, color: "#E08A3C", defaultScale: [1, 1, 1],
      uncertain: true,
      model: "CaptureFlagSpawnPointTeam2", icon: "Icon_PurpleTeamFlag" },
    ],
  },
];
